/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.FuncionarioDao;
import DTO.FuncionarioDto;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Visualizar extends javax.swing.JFrame {

    /**
     * Creates new form visualizar
     */
    public Visualizar() {
        initComponents();
        listarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        btnCadastrar = new javax.swing.JButton();
        headCadsatra1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTabela = new javax.swing.JTable();
        btnCadastrar3 = new javax.swing.JButton();
        btnVisu3 = new javax.swing.JButton();
        btnEditar3 = new javax.swing.JButton();

        jMenuBar1.setBackground(new java.awt.Color(241, 245, 235));
        jMenuBar1.setForeground(new java.awt.Color(3, 72, 51));
        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(10, 10, 10, 0));

        jMenu1.setBackground(new java.awt.Color(241, 245, 235));
        jMenu1.setForeground(new java.awt.Color(0, 159, 111));
        jMenu1.setText("CADASTRAR FUNCIONARIO");
        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(3, 72, 51));
        jMenu2.setText("VISUALIZAR");
        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(3, 72, 51));
        jMenu3.setText("EDITAR");
        jMenuBar1.add(jMenu3);

        btnCadastrar.setBackground(new java.awt.Color(131, 205, 32));
        btnCadastrar.setForeground(java.awt.Color.white);
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        headCadsatra1.setBackground(new java.awt.Color(241, 245, 235));
        headCadsatra1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        headCadsatra1.setForeground(new java.awt.Color(3, 72, 51));
        headCadsatra1.setText("CADASTRAR FUNCIONARIO");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 245, 235));

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(3, 72, 51));
        jLabel1.setText("VISUALIZAÇÃO DOS FUNCIONÁRIOS");

        txtTabela.setBackground(new java.awt.Color(209, 229, 178));
        txtTabela.setForeground(java.awt.Color.black);
        txtTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MATRÍCULA", "NOME", "FUNÇÃO", "TREINAMENTO", "STATUS TREINAMENTO"
            }
        ));
        txtTabela.setSelectionBackground(java.awt.Color.white);
        txtTabela.setSelectionForeground(java.awt.Color.black);
        jScrollPane1.setViewportView(txtTabela);

        btnCadastrar3.setBackground(new java.awt.Color(241, 245, 235));
        btnCadastrar3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnCadastrar3.setForeground(new java.awt.Color(3, 72, 51));
        btnCadastrar3.setText("CADASTRAR FUNCIONARIO");
        btnCadastrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrar3ActionPerformed(evt);
            }
        });

        btnVisu3.setBackground(new java.awt.Color(241, 245, 235));
        btnVisu3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnVisu3.setForeground(new java.awt.Color(3, 72, 51));
        btnVisu3.setText("VISUALIZAR");

        btnEditar3.setBackground(new java.awt.Color(241, 245, 235));
        btnEditar3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnEditar3.setForeground(new java.awt.Color(3, 72, 51));
        btnEditar3.setText("EDITAR");
        btnEditar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnCadastrar3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVisu3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar3)
                .addContainerGap(439, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar3)
                    .addComponent(btnVisu3)
                    .addComponent(btnEditar3))
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnEditar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar3ActionPerformed
        new Editar().setVisible(true);
    }//GEN-LAST:event_btnEditar3ActionPerformed

    private void btnCadastrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrar3ActionPerformed
        new Cadastro().setVisible(true);    
    }//GEN-LAST:event_btnCadastrar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
         
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

   
           
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
             
            public void run() {
//                new Visualizar().listarValores(); 
                new Visualizar().setVisible(true);                                   
                
            }
        });
        
               
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCadastrar3;
    private javax.swing.JButton btnEditar3;
    private javax.swing.JButton btnVisu3;
    private javax.swing.JButton headCadsatra1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable txtTabela;
    // End of variables declaration//GEN-END:variables

    public void listarValores() {

        FuncionarioDao funcioarioDao = new FuncionarioDao();
        DefaultTableModel model = (DefaultTableModel) txtTabela.getModel();
        model.setNumRows(0);

        ArrayList<FuncionarioDto> lista = funcioarioDao.PesquisarFuncionario();

        for (int i = 0; i < lista.size(); i++) {

            model.addRow(new Object[]{
                lista.get(i).getMatricula(),
                lista.get(i).getNomeFuncionario(),
                lista.get(i).getFuncaoFuncionario(),
                lista.get(i).getTreinamentoFuncionario(),
                lista.get(i).getStatusFuncionario(),});

        }
    }
}
